job_environments:
  common_environment: &common_environment
    CONTAINER_PREFIX: planet4-defaultcontent
    APP_HOSTPATH: defaultcontent
    WP_DB_NAME_PREFIX: planet4-defaultcontent_wordpress
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: www-dev.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: defaultcontent
    HELM_RELEASE: planet4-defaultcontent
    WP_DB_NAME: planet4-defaultcontent_wordpress
    WP_STATELESS_BUCKET: planet4-defaultcontent-stateless-develop