job_environments:
  common_environment: &common_environment
    CONTAINER_PREFIX: planet4-defaultcontent
    APP_HOSTPATH: defaultcontent
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: www-dev.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GCLOUD_CLUSTER: p4-development
    GOOGLE_PROJECT_ID: planet-4-151612
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-defaultcontent
    NEWRELIC_APPNAME: P4 Defaultcontent Development
    WP_DB_NAME: planet4-defaultcontent_wordpress
    WP_STATELESS_BUCKET: planet4-defaultcontent-stateless-develop