---
version: 2.1

docker_auth: &docker_auth
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD

defaults: &defaults
  docker:
    - image: greenpeaceinternational/p4-builder:latest
      auth:
        <<: *docker_auth

job_environments:
  common_environment: &common_environment
    CONTAINER_PREFIX: planet4-defaultcontent
    APP_HOSTPATH: defaultcontent
    WP_DB_NAME_PREFIX: planet4-defaultcontent_wordpress
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: www-dev.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-defaultcontent
    NEWRELIC_APPNAME: P4 Defaultcontent Development
    WP_DB_NAME: planet4-defaultcontent_wordpress
    WP_STATELESS_BUCKET: planet4-defaultcontent-stateless-develop

job_definitions:
  build_steps: &build_steps
    working_directory: ~/
    steps:
      - setup_remote_docker
      - run: activate-gcloud-account.sh
      - run: mkdir -p /tmp/workspace/var
      - run: mkdir -p /tmp/workspace/src
      - run: echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num
      - run: make
      - run:
          name: Notify failure
          when: on_fail
          command: TYPE="Build" notify-job-failure.sh
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - var
            - src

  prepare_release: &prepare_release
    working_directory: /tmp/workspace/src
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: release-prepare-nro.sh
      - run:
          name: Notify failure
          when: on_fail
          command: TYPE="Prepare" notify-job-failure.sh
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - var
            - src

  notify_promote: &notify_promote
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: notify
          command: |
            TYPE="@rawalker Promote release/$(increment-version.sh "$(git-current-tag.sh)")" \
            EXTRA_TEXT="Verify: https://$APP_HOSTNAME/$APP_HOSTPATH" \
            notify-job-hold.sh

  notify_hold: &notify_hold
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: notify
          command: |
            TYPE="@rawalker Hold: ${CIRCLE_TAG}" \
            EXTRA_TEXT="Verify: https://$APP_HOSTNAME/$APP_HOSTPATH" \
            notify-job-hold.sh

  finish_release: &finish_release
    working_directory: /tmp/workspace/src
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: increment-version.sh "$(git-current-tag.sh)" | tee /tmp/workspace/var/new_release
      - run: release-finish.sh
      - run: git push origin --delete release/$(cat /tmp/workspace/var/new_release)
      - run:
          name: Notify failure
          when: on_fail
          command: TYPE="Promote" notify-job-failure.sh

  deploy_steps: &deploy_steps
    working_directory: ~/
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: activate-gcloud-account.sh
      - run: BUILD_TAG=build-$(cat /tmp/workspace/var/circle-build-num) make -j2 deploy

jobs:
  build-branch:
    <<: *defaults
    environment:
      <<: *common_environment
      <<: *develop_environment
    <<: *build_steps

  deploy-develop:
    <<: *defaults
    environment:
      <<: *common_environment
      <<: *develop_environment
    <<: *deploy_steps

  create-default-sql:
    docker:
      - image: greenpeaceinternational/circleci-base:latest
        auth:
          <<: *docker_auth
    environment:
      APP_HOSTNAME: k8s.p4.greenpeace.org
      APP_HOSTPATH: defaultcontent
      CLOUDSQL_INSTANCE: p4-develop-k8s
      CONTAINER_PREFIX: planet4-defaultcontent
      GOOGLE_PROJECT_ID: planet-4-151612
      HELM_NAMESPACE: develop
      INFRA_VERSION: develop
      NEWRELIC_APPNAME: Planet4 Default Content Development
      WP_DB_NAME: planet4-defaultcontent_wordpress
      WP_TITLE: Greenpeace Default Content
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Configure
          command: |
            ${HOME}/scripts/activate-gcloud-account.sh
      - run: echo $SQLPROXY_KEY | base64 -d > key.json
      - run: SQL_TAG=$CIRCLE_TAG make -j2
      - run:
          name: Update nro-generator with the latest tag
          command: bash update_nro_generator.sh
      - run:
          name: Update docker-compose with the latest tag
          command: bash update_docker_compose.sh

  create-test-data:
    <<: *defaults
    environment:
      <<: *common_environment
      <<: *develop_environment
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: /home/circleci/run_bash_script_in_php_pod.sh ./generate-test-content.sh /tmp/workspace
      - store_artifacts:
          path: /tmp/workspace

workflow_definitions:
  develop_common: &develop_common
    context: org-global
    filters:
      branches:
        only: develop

workflows:
  version: 2
  develop:
    jobs:
    - build-branch:
        <<: *develop_common
    - deploy-develop:
        <<: *develop_common
        requires:
          - build-branch
    - create-test-data:
        <<: *develop_common
        requires:
          - deploy-develop

  create-default-sql:
    jobs:
    - create-default-sql:
        context: org-global
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v.*/
