defaults: &defaults
  docker:
    - image: gcr.io/planet-4-151612/p4-builder:develop
  working_directory:  /home/circleci/

version: 2

jobs:
  build-develop:
    <<: *defaults
    environment:
      APP_HOSTNAME: k8s.p4.greenpeace.org
      APP_HOSTPATH: defaultcontent
      CLOUDSQL_INSTANCE: p4-develop-k8s
      CONTAINER_PREFIX: planet4-defaultcontent
      GOOGLE_PROJECT_ID: planet-4-151612
      HELM_NAMESPACE: develop
      INFRA_VERSION: develop
      WP_DB_NAME: planet4-defaultcontent_wordpress
      WP_TITLE: Greenpeace Default Content
    steps:
      - setup_remote_docker

      - run:
          name: Configure
          command: |
            ${HOME}/scripts/activate-gcloud-account.sh
            mkdir -p /tmp/workspace/var
            echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num

      - run:
          name: Build
          working_directory: /home/circleci
          command: |
            if make
            then
              TYPE="Build" ${HOME}/scripts/notify-job-success.sh
            else
              TYPE="Build" ${HOME}/scripts/notify-job-failure.sh
              exit 1
            fi

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - var

  # test:
  #   <<: *defaults
  #   steps:
  #     - run:
  #         name: Placeholder
  #         command: |
  #           echo "Branch: ${CIRCLE_BRANCH}"
  #           echo "Build:  ${CIRCLE_BUILD_NUM}"
  #           echo "Tag:    ${CIRCLE_TAG}"
  #           echo "No tests implemented yet"

  deploy-develop:
    <<: *defaults
    environment:
      APP_HOSTNAME: k8s.p4.greenpeace.org
      APP_HOSTPATH: defaultcontent
      CLOUDSQL_INSTANCE: p4-develop-k8s
      CONTAINER_PREFIX: planet4-defaultcontent
      GOOGLE_PROJECT_ID: planet-4-151612
      HELM_NAMESPACE: develop
      INFRA_VERSION: develop
      NEWRELIC_APPNAME: Planet4 Default Content Development
      WP_DB_NAME: planet4-defaultcontent_wordpress
      WP_TITLE: Greenpeace Default Content
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Configure
          command: |
            ${HOME}/scripts/activate-gcloud-account.sh

      - run:
          name: Deploy new containers
          environment:
          command: |
            export BUILD_TAG=build-$(cat /tmp/workspace/var/circle-build-num)
            make deploy

  create-default-sql:
    docker:
      - image: gcr.io/planet-4-151612/circleci-base:latest
    environment:
      APP_HOSTNAME: k8s.p4.greenpeace.org
      APP_HOSTPATH: defaultcontent
      CLOUDSQL_INSTANCE: p4-develop-k8s
      CONTAINER_PREFIX: planet4-defaultcontent
      GOOGLE_PROJECT_ID: planet-4-151612
      HELM_NAMESPACE: develop
      INFRA_VERSION: develop
      NEWRELIC_APPNAME: Planet4 Default Content Development
      WP_DB_NAME: planet4-defaultcontent_wordpress
      WP_TITLE: Greenpeace Default Content
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Configure
          command: |
            ${HOME}/scripts/activate-gcloud-account.sh
      - run: echo $SQLPROXY_KEY | base64 -d > key.json
      - run: SQL_TAG=$CIRCLE_TAG make -j2
      - run:
          name: Checkout nro-generator
          command: git clone https://github.com/greenpeace/planet4-nro-generator
      - run:
          name: Switch to project nro-generator
          command: cd planet4-nro-generator/
      - run:
          name: Replace the version of the sql
          command: sed -i "s/planet4-defaultcontent_wordpress-.*.sql/planet4-defaultcontent_wordpress-v${SQL_TAG}.sql/g" Dockerfile


workflows:
  version: 2
  develop:
    jobs:
    - build-develop:
        context: org-global
        filters:
          branches:
            only: develop
          tags:
            ignore: /^v.*/

    - deploy-develop:
        context: org-global
        requires:
          - build-develop
        filters:
          branches:
            only: develop
  create-default-sql:
    jobs:
    - create-default-sql:
        context: org-global
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v.*/
