---
version: 2.1

docker_auth: &docker_auth
  username: $DOCKERHUB_USERNAME
  password: $DOCKERHUB_PASSWORD

defaults: &defaults
  docker:
    - image: greenpeaceinternational/p4-builder:latest
      auth:
        <<: *docker_auth

job_environments:
  common_environment: &common_environment
    CONTAINER_PREFIX: planet4-defaultcontent
    APP_HOSTPATH: defaultcontent
    WP_DB_NAME_PREFIX: planet4-defaultcontent_wordpress
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: www-dev.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: defaultcontent
    HELM_RELEASE: planet4-defaultcontent
    WP_DB_NAME: planet4-defaultcontent_wordpress
    WP_STATELESS_BUCKET: planet4-defaultcontent-stateless-develop

job_definitions:
  build_steps: &build_steps
    working_directory: ~/
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          if [[ -d source/cache ]]; then ls -al source/cache; fi
      - run: activate-gcloud-account.sh
      - run: mkdir -p /tmp/workspace/var /tmp/workspace/src
      - run: echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num
      - run: make test
      - run: make rewrite
      - run: make checkout
      - run: make rewrite-app-repos
      - run: make copy
      - run: make bake
      - run: make persist
      - run: make build
      - run: make push
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - var
            - src

  deploy_steps: &deploy_steps
    working_directory: ~/
    steps:
      - checkout:
          path: /home/circleci/checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: activate-gcloud-account.sh
      - run: make prepare-helm
      - run: make backup
      - run: BUILD_TAG=build-$(cat /tmp/workspace/var/circle-build-num) make deploy-helm
      - run: make post-deploy

jobs:
  build:
    <<: *defaults
    environment:
      <<: *common_environment
      <<: *develop_environment
    <<: *build_steps

  deploy:
    <<: *defaults
    environment:
      <<: *common_environment
      <<: *develop_environment
    <<: *deploy_steps

  create-default-sql:
    docker:
      - image: greenpeaceinternational/circleci-base:latest
        auth:
          <<: *docker_auth
    environment:
      APP_HOSTNAME: k8s.p4.greenpeace.org
      APP_HOSTPATH: defaultcontent
      CLOUDSQL_INSTANCE: p4-develop-k8s
      CONTAINER_PREFIX: planet4-defaultcontent
      GOOGLE_PROJECT_ID: planet-4-151612
      HELM_NAMESPACE: develop
      INFRA_VERSION: develop
      NEWRELIC_APPNAME: Planet4 Default Content Development
      WP_DB_NAME: planet4-defaultcontent_wordpress
      WP_TITLE: Greenpeace Default Content
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Configure
          command: |
            activate-gcloud-account.sh
      - run: echo $SQLPROXY_KEY | base64 -d > key.json
      - run: SQL_TAG=$CIRCLE_TAG make -j2
      - run:
          name: Update nro-generator with the latest tag
          command: ./bin/update_nro_generator.sh
      - run:
          name: Update docker-compose with the latest tag
          command: ./bin/update_docker_compose.sh
      - run:
          name: Update develop environment with the latest tag
          command: ./bin/update_develop.sh

workflow_definitions:
  develop_common: &develop_common
    context: org-global
    filters:
      branches:
        only: main

workflows:
  develop:
    jobs:
      - build:
          <<: *develop_common
      - deploy:
          <<: *develop_common
          requires:
            - build

  create-default-sql:
    jobs:
      - create-default-sql:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
